# Generated by Django 2.0.2 on 2018-02-17 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180217_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
