# Generated by Django 2.0.2 on 2018-02-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180218_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='cat',
            new_name='category',
        ),
    ]
